### ISSUE TITLE
功能改进

### ISSUE THREAD

**Issue by daomengRen** [AKclown/file-teleport#1]
能不能实现像git那样，对出现差异的每一行增加一个箭头，然后通过点击箭头直接去实现每一行的update操作，当然，目前这样也是可以的

**Comment by AKclown** [comment]
感谢你的建议，等有空闲时间我将尝试你所说的

**Comment by daomengRen** [comment]
谢谢 支持

**Comment by AKclown** [comment]
抱歉让你久等了，最近都忙于别的事情。
模板结构已经初步实现，  目前官方好像不提供gutterIcon的点击事件，问题链接如下，我将会跟进这个问题，等有最新进展我将会通知你
[#5455](https://github.com/microsoft/vscode/issues/5455)

模板结构，目前想法是，删除/新增，我会新增空行来实现行数对应，如果你又更好的想法请告诉我，感谢
![image](https://user-images.githubusercontent.com/33648653/132458847-0e11117c-8e29-472a-b39a-b9545dbda206.png)

**Comment by daomengRen** [comment]
> 抱歉让你久等了，最近都忙于别的事情。
> 模板结构已经初步实现， 目前官方好像不提供gutterIcon的点击事件，问题链接如下，我将会跟进这个问题，等有最新进展我将会通知你
> [#5455](https://github.com/microsoft/vscode/issues/5455)
> 
> 模板结构，目前想法是，删除/新增，我会新增空行来实现行数对应，如果你又更好的想法请告诉我，感谢
> ![image](https://user-images.githubusercontent.com/33648653/132458847-0e11117c-8e29-472a-b39a-b9545dbda206.png)

没事，现在的功能应该就可以了，再次感谢。
